// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8yUAzoePGt6IWh2fYSgIsxvsao0-YvVU',
    appId: '1:473791988007:web:81649b094804b5f4e3e902',
    messagingSenderId: '473791988007',
    projectId: 'fir-auth-5b127',
    authDomain: 'fir-auth-5b127.firebaseapp.com',
    storageBucket: 'fir-auth-5b127.firebasestorage.app',
    measurementId: 'G-02JG438PYR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-O6o_9K_nxwuXmFyNurPLqNPOIvMbogc',
    appId: '1:473791988007:android:45f5b825e028cc55e3e902',
    messagingSenderId: '473791988007',
    projectId: 'fir-auth-5b127',
    storageBucket: 'fir-auth-5b127.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwmsEQaunI6-tIyh79I1lWVyJ9PnCls4Q',
    appId: '1:473791988007:ios:0090b8756102073be3e902',
    messagingSenderId: '473791988007',
    projectId: 'fir-auth-5b127',
    storageBucket: 'fir-auth-5b127.firebasestorage.app',
    iosBundleId: 'com.example.widgetsPracticing',
  );

}